### PR TITLE
Adding files for test purposes

### PR DESCRIPTION
**Pull request by mwobensmith**

### CODE REVIEW

**Comment by fmarier** [comment]
Which test are these files related to? Can we name them in such a way that we'll remember what they're for?

I'm thinking that in 6 months, someone might can back to this repo, notice that the html file doesn't use these generically-named files and just remove them (thereby breaking the tests).

**Comment by mwobensmith** [comment]
I intend to use them in a Fx UI test that I am writing now. I'm open to naming them anything. How about "test.jpg" and "test.css"?

**Comment by fmarier** [comment]
In that case maybe `fxui-test.jpg` and `fxui-test.css`?

**Comment by mwobensmith** [comment]
There you go.

**Comment by fmarier** [comment]
Thanks Matt.

**Pull request merged**
